### ISSUE TITLE
Generate sellerFulfillmentOrderId for AmazonFulfillmentOrderCreator

### ISSUE THREAD

**Issue by novavex** [CPIGroup/phpAmazonMWS#107]
The fulfillmentordercreator class indicates I should get the shipment ID from amazonfulfillmentpreview, but that doesn't seem to be returned anywhere in that class.

I'm looking at the documentation

http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_GetFulfillmentPreview.html

Is the sellerFulfillmentOrderId the same as the request Id? If so, how would I access that?

**Comment by Peardian** [comment]
Based on the current documentation, it looks like you create the ID entirely by yourself. I don't have access to the old documents I used, so I don't know whether they changed the API or the documentation was worded differently. Either way, I'll have to update the documentation. Thank you for bringing it to my attention.

**Comment by novavex** [comment]
Awesome, yeah, that worked. Thanks for the super swift reply.
