### ISSUE TITLE
List all products in my store

### ISSUE THREAD

**Issue by bado57** [CPIGroup/phpAmazonMWS#110]
Hi everyone, Im install framework, but I am not found List all products in my store. How do it?

**Comment by bado57** [comment]
Which library I need to use or functions.

**Comment by Peardian** [comment]
Because of how big the list can be, Amazon does not let you get a full list of products with a regular API request. Instead, you must request a report. The process is like this:
1. Use an `AmazonReportRequest` object to request a report. You can find the list of possible report types inside the `setReportType` method.
2. Use an `AmazonReportRequestList` object to check on the status of your reports.
3. When the report has finished processing, use an `AmazonReport` object to download it.
4. Once you have successfully received the report, use an `AmazonReportAcknowledger` object to tell Amazon that you have received it.

**Comment by bado57** [comment]
Thanks, So  AmazonReportRequest object return report ID than use it with AmazonReportRequestList chechk status. If the report is prepared we will download it and finally We will tell this to amazon ??

For example first condition;
function getAmazonReportRequest() {
    try {
        $amz = new AmazonReportRequest("piccadillybookstore");
        $amz->setReportType("_GET_MERCHANT_LISTINGS_DATA_"); //exclude cancelled feeds
        $amz->setTimeLimits("2014-01-01", "-1 hour");
        $amz->setMarketplaces("ATVPDKIKX0DER");
        $amz->requestReport();
        return $amz->getResponse();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

print_r(getAmazonReportRequest());

First condition return reportID and than  how use it ? Please show me code sample. I did a lot of hard work, but it never happened.

Thanks everythink.

**Comment by Peardian** [comment]
It looks like you've done the first step correctly. Now that you have the report request ID, you can pass it to the `setRequestIds` method of the `AmazonReportRequestList` object. This will tell you the report ID when it is finished, which you can give to the `AmazonReport` class.

**Comment by bado57** [comment]
Thanks second part AmazonReportRequestList object, setRequestIds method return null.How it looks 2. part;

```
function getAmazonReportRequestList() {
    try {
        $amz = new AmazonReportRequestList("piccadillybookstore");
        $amz->setRequestIds("50082017171");
        $amz->setReportTypes("_GET_MERCHANT_LISTINGS_DATA_");
        return $amz->getStatus();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

$result = getAmazonReportRequestList();
print_r($result);
```

Do not you have to use token ? thank you for your help.

**Comment by bado57** [comment]
Hi @Peardian , I have tried many alternatives for this situation but the result is empty.  In many forums this has always been the case and the answers to the questions have not been found. If you give your answer here, it will be a good example of this question

The situation I came up with is;


```
function getAmazonReportRequestList() {
    try {
        $amzz = new AmazonReportRequestList("piccadillybookstore");
        $amzz->setRequestIds("50092017172");
        $amzz->setReportTypes("_GET_MERCHANT_LISTINGS_DATA_");
        $amzz->setReportStatuses("_IN_PROGRESS_");
        return $amzz->getList();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

$result = getAmazonReportRequestList();
print_r($result);
```

Should I wait for the report to be ready immediately after sending the report request?

**Comment by Peardian** [comment]
For getting the report request list, you may need the token if you have a lot of reports. If you only have a few reports, you will not need to use the token, but the safest way to get what you need is to always enable the token.

For your searching, it looks like you are putting too many search filters. If you already know the request ID to search for, you don't need to filter out based on type or status.

**Comment by bado57** [comment]
Thank you so much for your help. Do I have a chance to get xson yada json report ?

**Comment by Peardian** [comment]
The format of the report is whatever Amazon gives you and depends on the type of report you request. My library has no control over that.

**Comment by bado57** [comment]
So send request with curl use to json or xml  header?

**Comment by bado57** [comment]
Hi instead of pulling the whole list, how do we attract the feature I want. For example, only the ISBN number?

**Comment by Peardian** [comment]
I am not sure what your first question is asking. If you are asking about how to send the message that fetches the request, the library takes care of that already. If you are asking whether you should choose XML or Flat File for the report type, that is something you have to decide for yourself.

As for your second question, that is not something Amazon has made features for. All of the reports that Amazon has are in the list I showed you. If you only want the ISBN, you will have to filter the data yourself.
