### ISSUE TITLE
Lowest Price

### ISSUE THREAD

**Issue by users57** [CPIGroup/phpAmazonMWS#111]
Thank you very much for your library. I am running this code but it returns more than one price instead of a single price, and the returned prices are not the lowest. You have a mistake. Can you check ?

```
function getAmazonProductPriceDownload() {
    try {
        $amzp = new AmazonProductInfo("mystore");
        $amzp->setSKUs("978-0425272947");
        $amzp->setConditionFilter("New");
        $amzp->fetchLowestOffer();
        return $amzp->getProduct();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

print_r(getAmazonProductPriceDownload());
```

Thanks everything.

**Comment by Peardian** [comment]
The `fetchLowestOffer` method simply sends a `GetLowestOfferListingsForSKU` request to Amazon's API. I have no control over the content of the data they send. You can read the official documentation for the API here:

http://docs.developer.amazonservices.com/en_US/products/Products_GetLowestOfferListingsForSKU.html

**Comment by bado57** [comment]
Thank you I have solved the problem. One last question on this subject is; I am questioning the lowest store price, but the answer is that one situation is turning around. So the new situation does not come. The only used-good condition is returning. But the site [()](http://docs.developer.amazonservices.com/en_US/products/Products_GetCompetitivePricingForASIN.html) can be turned into questioning in two cases


```
function getAmazonProductPriceDownload() {
    try {
        $amzp = new AmazonProductInfo("piccadillybookstore");
        $amzp->setSKUs("978-0425272947");
        $amzp->fetchCompetitivePricing();
        return $amzp->getProduct();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

print_r(getAmazonProductPriceDownload());
```

**Comment by Peardian** [comment]
Again, I have no control over what data Amazon gives.

**Comment by bado57** [comment]
So, Are you sure that this function for any Product gives you the lowest list price in all stores?

**Comment by bado57** [comment]
Are you sure that this function for any Product gives you the lowest list price in all stores?

**Comment by Peardian** [comment]
Once again, I have no control over what data Amazon gives through their `GetLowestOfferListingsForSKU` API command. If you have a concern over the data given by Amazon, contact Amazon.

**Comment by bado57** [comment]
Thank you for your clarifications

**Comment by bado57** [comment]
One last question; MarketplaceIDs are among the parameters that are required in the [documents](https://docs.developer.amazonservices.com/en_MX/products/Products_GetLowestOfferListingsForSKU.html) , but we use the market name here. 

`$amzp = new AmazonProductInfo("mystore");`

Is this a problem?  On the other side; The above code is enough to find the lowest price ?

**Comment by Peardian** [comment]
The string you use when initiating objects for the library depends on the array key you chose when setting up your config file. The string itself has no bearing on the messages sent to Amazon.

**Comment by bado57** [comment]
Thank you but I do not try. The problem is; I want to find the lowest price for the products in the market. When I query with asin paremeter, everything is normal and I can get the lowest price.
```
function getAmazonProductPriceDownload2() {
    try {
        $amzf = new AmazonProductInfo();
        $amzf->setASINs("B003VS8MJE");
        $amzf->fetchLowestOffer();
        $amzf->setConditionFilter("Used");
        return $amzf->getProduct();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

print_r(getAmazonProductPriceDownload2());
```

 But when I trade with SKU, the lowest price value of SKU does not come up.

```
function getAmazonProductPriceDownload2() {
    try {
        $amzf = new AmazonProductInfo();
        $amzf->setSKUs("978-0072424119");
        $amzf->fetchLowestOffer();
        $amzf->setConditionFilter("Used");
        return $amzf->getProduct();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}

print_r(getAmazonProductPriceDownload2());
```

Again, the values of the above query. So it's the same asin with sku. You can cause this?

**Comment by Peardian** [comment]
Are you saying that you are getting no price data at all? Or are you getting price data that is not the lowest?

Double-check your data to make sure that the SKU you are sending is typed correctly and is for the same product as the ASIN. Additionally, you can use `getLastResponse()` to see the raw message that Amazon returned.

**Comment by bado57** [comment]
I'm just querying for the lowest price.ASIN and SKU value are the same product.But according to the sku value the result is the same as the ASIN value.You know that the ASIN and SKU lowest prices have to be different.The results are still the same for the your library. Please help this condition very important.

**Comment by bado57** [comment]
I can get the lowest price of the product according to the right product with fetchLowestOffer() function.But the lowest prices I found are the same as ASIN prices.

**Comment by bado57** [comment]
`Array ( [head] => HTTP/1.1 200 OK Server: Server Date: Tue, 10 Jan 2017 18:32:18 GMT Content-Type: text/xml Transfer-Encoding: chunked Connection: keep-alive x-mws-quota-max: 36000.0 x-mws-quota-remaining: 35998.0 x-mws-quota-resetsOn: 2017-01-10T18:38:00.000Z x-mws-response-context: GeoQ6erCxuDvlFsUxOd1lkiFDAtCCwYGeD3umC/AZudtUrkZdyRiyG8P5A6lQw+yYMHgf5HA2xE= x-mws-response-context: D0x/T7IHiWPJesRDh5sKeBRY0x+MEqXDvy43ZNo7bIWYheLj0DhRcuAhsGgNDq8LiekoKNzUxooD Znbsp/wT7g== x-amz-request-id: ebeacdd1-cd7d-4cde-b887-af9b7a71162e x-mws-request-id: ebeacdd1-cd7d-4cde-b887-af9b7a71162e x-mws-timestamp: 2017-01-10T18:32:18.803Z Vary: Accept-Encoding,User-Agent [body] => falseATVPDKIKX0DERB003VS8MJEATVPDKIKX0DERA1DQ8DH0ETPS24978-0072424119UsedGoodMerchantTrue0-2 days95-97%3310USD43.18USD39.19USD3.99TrueUsedGoodMerchantTrue0-2 days98-100%81957USD43.19USD39.20USD3.99TrueUsedGoodMerchantUnknown0-2 days98-100%46868USD43.19USD39.20USD3.99FalseUsedAcceptableMerchantTrue0-2 days98-100%1146200USD43.20USD39.21USD3.99FalseUsedAcceptableMerchantUnknown0-2 days98-100%111081USD44.63USD40.64USD3.99FalseUsedGoodMerchantUnknown3-7 days98-100%269527USD45.89USD41.90USD3.99TrueUsedAcceptableMerchantUnknown3-7 days98-100%140968USD45.89USD41.90USD3.99Falseebeacdd1-cd7d-4cde-b887-af9b7a71162e [code] => 200 [answer] => OK [ok] => 1 [headarray] => Array ( [Server] => Server [Date] => Tue, 10 Jan 2017 18:32:18 GMT [Content-Type] => text/xml [Transfer-Encoding] => chunked [Connection] => keep-alive [x-mws-quota-max] => 36000.0 [x-mws-quota-remaining] => 35998.0 [x-mws-quota-resetsOn] => 2017-01-10T18:38:00.000Z [x-mws-response-context] => D0x/T7IHiWPJesRDh5sKeBRY0x+MEqXDvy43ZNo7bIWYheLj0DhRcuAhsGgNDq8LiekoKNzUxooD Znbsp/wT7g== [x-amz-request-id] => ebeacdd1-cd7d-4cde-b887-af9b7a71162e [x-mws-request-id] => ebeacdd1-cd7d-4cde-b887-af9b7a71162e [x-mws-timestamp] => 2017-01-10T18:32:18.803Z [Vary] => Accept-Encoding,User-Agent ) ) `

**Comment by bado57** [comment]
That is, the return result for ASIN is correct, the return result for SKU value is the same as ASIN result

**Comment by Peardian** [comment]
Maybe there is something that I am not understanding, but I don't see what the problem is. If you use the ASIN of an item to get prices, and then use the ASIN of that same item to get prices, should it not be returning the same prices, because both IDs refer to the same item? Why would it be different?

**Comment by bado57** [comment]
**Normally the SKU and ASIN results should be different for the lowest price.**

I can tell you that way. I am trying to find the lowest price in all the stores of a product. I use the SKU value of the product to find the lowest rate.When we look for amazon market

```
 $amzf = new AmazonProductInfo();
        $amzf->setSKUs("978-0072424119");
        $amzf->fetchLowestOffer();
        $amzf->setConditionFilter("Used");
        return $amzf->getProduct();
```

I do the same ASIN value search;

 ```
$amzf = new AmazonProductInfo();
        $amzf->setASINs("B003VS8MJE");
        $amzf->fetchLowestOffer();
        $amzf->setConditionFilter("Used");
        return $amzf->getProduct();
```

ASIN value and SKU value are the same product. The same results for the same products.

**Normally these results should be different**

I hope I can tell

**Comment by bado57** [comment]
You can try it out if you want. Enter Amazon.com. Search by SKU and ASIN value.

SKU: 978-0072424119
ASIN : B003VS8MJE

You will see that the same products have different results.

https://www.amazon.com/  

You can type values into the search field

**Comment by Peardian** [comment]
I see that the search results on the website are different. However, as I said before, the library has no control over the price data that Amazon is sending to you. If you were to directly send a REST request to Amazon's Product API, you would receive the exact same data.

If you have a concern over the data given by Amazon, contact Amazon.
