### ISSUE TITLE
How to update minumum pricing products?

### ISSUE THREAD

**Issue by users57** [CPIGroup/phpAmazonMWS#112]
Hi, how can I update the minimum price for multiple products at the same time. As far as I can tell from the library, it needs to be done in a few steps. Could you tell me these steps? Which class has which function?

On the other hand;

How to set the feed value in the example you are doing? 

```
function sendInventoryFeed($feed) {
    try {
        $amz = new AmazonFeed(); //if there is only one store in config, it can be omitted
        $amz->setFeedType("_POST_INVENTORY_AVAILABILITY_DATA_"); //feed types listed in documentation
        $amz->setFeedContent($feed); //can be either XML or CSV data; a file upload method is available as well
        $amz->submitFeed(); //this is what actually sends the request
        return $amz->getResponse();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
    }
}
```

Thanks.

**Comment by Peardian** [comment]
Product listings are created and updated using feeds. See these previous issues for more information:
#59
#105

**Comment by Peardian** [comment]
Since there have not been any follow-up response, I am assuming that the links I provided have answered your questions.
