### ISSUE TITLE
AmazonCore.php timestamp 

### ISSUE THREAD

**Issue by bado57** [CPIGroup/phpAmazonMWS#114]
Hi,  Why are you using it like this;

` return date('Y-m-d\TH:i:sO', $time -120);`
AmazonCore.php line 569

Why do you subtract 120 from the time value ?

**Comment by Peardian** [comment]
This is already explained in the function's phpdocs, but I feel I can explain it a bit more. In the past, we experienced issues in which Amazon thought we were sending "future" time values when we sent the current time. Subtracting two minutes (120 seconds) from the time solved the issue. I do not know if the problem still occurs.

**Comment by Peardian** [comment]
Seeing as there have been no further responses, I am going to assume that the question has been satisfactorily answered.
