### ISSUE TITLE
Laravel Integration

### ISSUE THREAD

**Issue by mpixelz** [CPIGroup/phpAmazonMWS#115]
Hi,
ive been using peron laravel mws branch of this project.. but was just wondering if there is an easier way to use this git on laravel project so its always updated with the original library?
thanks.

**Comment by Peardian** [comment]
I'm afraid I am not able to answer this question. The Laravel fork is maintained entirely by someone else, and I have no knowledge of how to use Laravel. You will have to ask someone who maintains one of the Laravel forks.
