### ISSUE TITLE
ASIN  to ISBN

### ISSUE THREAD

**Issue by bado57** [CPIGroup/phpAmazonMWS#116]
Hi, I want to get your ISBN number 10 using your library. How can I do this and what class I need to use?
I did a lot of amazon documentation to get the ISBN number 10 by API.But no results were found.

Please be very happy if you can help. Thank you.

**Comment by Peardian** [comment]
I am not very familiar with product listings, so I do not have a direct answer for you. However, I am certain that you will need to use either one of the Products core classes (for example, `AmazonProductInfo`), or a product-related report. That is as far as I can help you with this question.

**Comment by Peardian** [comment]
Seeing as there have been no followup questions, I am going to close this.
