### ISSUE TITLE
Full client library

### ISSUE THREAD

**Issue by lrjbrual** [CPIGroup/phpAmazonMWS#118]
Hi, I would like to ask if this package are included the following details:

FBAInboundServiceMWS	
FBAOutboundServiceMWS
MarketplaceWebService
MarketplaceWebServiceOrders	
MarketplaceWebServiceProducts	
MarketplaceWebServiceSellers
MWSCartService
MWSCustomerService	
MWSFinancesService
MWSMerchantFulfillmentService	
MWSRecommendationsSectionService	
MWSSubscriptionsService	

Hope to hear you soon. we are currently developing new app using MWS API, if this will fit we will use it. let me know. 

Thank you for your contribution. :)

**Comment by livehybrid** [comment]
Id suggest looking through here to decide if it does all the things you need.
https://github.com/CPIGroup/phpAmazonMWS/tree/stable/includes/classes

Will

**Comment by Peardian** [comment]
The list sounds like it matches up with the list of Amazon MWS APIs, most of which this library does support. However, there are a few which are not supported.
* The Finances API is not supported yet, as it is relatively new.
* The Cart, Customer, and Webstore APIs are deprecated, as the Amazon Webstore service ended six months ago.

I hope you find this library useful, even if it does not meet your full requirements.

**Comment by lrjbrual** [comment]
@Peardian thank you for the information. we will take some review on this. then if good we will use it. I will let you know. and if this will good, we will try also to contribute. thanks again.

**Comment by lrjbrual** [comment]
@Peardian do we have features, that we can use multiple authentication token and merchant id? hoping to hear you soon. Thank you

**Comment by Peardian** [comment]
Yes, the store array in the config file can support an unlimited number of different store keys, each with their own Merchant ID, MWSAuthToken, and so on. The first key in the array is the string that you pass when constructing each object.

In the (hopefully-near) future, you will be able to pass store configuration settings on the fly, but for right now, it must read from the config file.

**Comment by Peardian** [comment]
Since it has been two weeks since the last question, I am going to assume that this thread has served its purpose.
