### ISSUE TITLE
Today it stopped working

### ISSUE THREAD

**Issue by g-alfieri** [CPIGroup/phpAmazonMWS#119]
I don't know precisely how today I can't get orders from amazon using this library. Sourcecode didn't change.

```php
$amz = new AmazonOrderList("xxxxxx"); //store name matches the array key in the config file
 $amz->setLimits('Modified', "- 96 hours"); //accepts either specific timestamps or relative times 
 $amz->setFulfillmentChannelFilter("MFN"); //no Amazon-fulfilled orders
 $amz->setOrderStatusFilter(
                array("Unshipped", "PartiallyShipped", "Canceled", "Unfulfillable")
                ); //no shipped or pending orders
            
 $amz->setUseToken(); //tells the object to automatically use tokens right away
 $amz->fetchOrders(); //this is what actually sends the request
```

**Comment by Peardian** [comment]
What error message are you getting? And is the problem still occurring? Sometimes Amazon performs maintenance on a service, but I can't be sure that this is the case unless I know what the error message is.

**Comment by Peardian** [comment]
@g-alfieri Is there any update on this? Did you get it working again?

**Comment by Peardian** [comment]
I am going to assume that the problem was not an issue with the library and was taken care of.
