### ISSUE TITLE
[Question] Can I create new items on MWS with this library?

### ISSUE THREAD

**Issue by Mahmoudz** [CPIGroup/phpAmazonMWS#120]
First I'd like to thank you for making this nice library.

My question is does this library allows creating new items on MWS?! 
I just created a store, I want to be able to import products from another system on my MWS store, is that possible. If yes can you please link me to the test or class responsible for that. With any kind of advice. 

Best,

**Comment by Peardian** [comment]
Yes it can, though doing so is not straight-forward. See #59 for more information.

**Comment by Peardian** [comment]
Seeing as it has been over a week, I am going to assume that the information has answered your question.

**Comment by Mahmoudz** [comment]
@Peardian yep I was able to do it, Thanks.
