### ISSUE TITLE
My secret key not working

### ISSUE THREAD

**Issue by harshitnayak45** [CPIGroup/phpAmazonMWS#121]
I have created my developer account and gave developer ID to client. He gives me merchant Id, marketplaceId and MWS Auth Token.  I have used my access key Id and secret key. But i can't established the connection to amazon store.  It gives me " There was a problem with the Amazon library. Error: Secret Key is missing!" error. Can you please help me on that.

**Comment by Peardian** [comment]
The error message you are describing only occurs if the "secretKey" array key is not set in the `$store` array in the `amazon-config.php` file. Did you make sure to set up your config file just like the default config file?

**Comment by harshitnayak45** [comment]
Yes i have set in the amazon-config.php file. But that gives me error for secret key. Can you suggest more on this.

**Comment by harshitnayak45** [comment]
Please check the logs below
[Warning][2017/03/30 22:20:15 guest@182.70.240.48 AmazonCore.php:133 setStore] Store myStore does not exist!

[Urgent][2017/03/30 22:20:15 guest@182.70.240.48 AmazonOrderList.php:50 resetMarketplaceFilter] Marketplace ID is missing

**Comment by harshitnayak45** [comment]
I have fixed the error. That works now. I have set order status Pending and setFulfillmentChannelFilter to AFN. Pending order fetched but that do not have customer details. Can you let me know how can i get customer details from Pending order .  Please suggest.

**Comment by Peardian** [comment]
I am glad that you were able to get it working.

As for orders, the [official Amazon documentation](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_GetOrder.html) states that only limited customer information is given for Pending orders.
