### ISSUE TITLE
Increase time for fetching orders

### ISSUE THREAD

**Issue by harshitnayak45** [CPIGroup/phpAmazonMWS#123]
I have fetched the orders and order details with products as well. But when i set it to -24 hours my script have script timeout issue .  When i set -2 hours then it works fine. I have around 2500 orders a day from amazon. Can you help me how can i remove the script timeout issue.

**Comment by harshitnayak45** [comment]
I have one more question : Is our script fetches Replacement Order. Please let me know. I do not want Replacement Order to be fetched.

**Comment by Peardian** [comment]
The script timeout problem is likely part of your PHP settings. The library uses cURL with `CURLOPT_TIMEOUT` set to 0, so the library will wait as long as your PHP setup allows it to.

**Comment by harshitnayak45** [comment]
Where i can set CURLOPT_TIMEOUT to 0?

**Comment by Peardian** [comment]
As for your other question, I do not know for sure. I just checked the API documentation, and it seems they have added new data fields named `IsReplacementOrder` and `ReplacedOrderId`, but the library does not yet have support for these fields. If you need this information, you can use `getLastResponse` to view the raw XML.

**Comment by harshitnayak45** [comment]
I think script does not support PromotionDiscount field also. Please confirm.

**Comment by Peardian** [comment]
The library already has `CURLOPT_TIMEOUT` set to 0, it is your other PHP settings that need to be changed.

**Comment by harshitnayak45** [comment]
Where i can find the CURLOPT_TIMEOUT 0. I need to check.

**Comment by Peardian** [comment]
The library does support `PromotionDiscount`. You can access it by using `getPromotionDiscount` in the `AmazonOrderItemList` class.

**Comment by harshitnayak45** [comment]
Where i can check the CURL client is enabled. I have not found this in library.

**Comment by Peardian** [comment]
https://github.com/CPIGroup/phpAmazonMWS/blob/stable/includes/classes/AmazonCore.php#L763

This is where cURL is being used. This is as far as I can help you regarding the timeout problem.

**Comment by harshitnayak45** [comment]
Ok. What you suggest about PHP setting?

**Comment by Peardian** [comment]
Sorry, I can't help you with your personal PHP settings.

**Comment by harshitnayak45** [comment]
Hello @Peardian , I have one question. Is our API fetches multiple products with Single order Id. Please let me know.

**Comment by Peardian** [comment]
Are you referring to the `AmazonOrderItemList ` class's `fetchItems` method? If so, yes, it fetches all of the order's items at once, as indicated by the documentation. I suggest reading through the methods and documentation for classes you are interested in, as this may answer other questions you might have about using this library.

**Comment by harshitnayak45** [comment]
So it will automatically fetched multiple products with single order ID?

**Comment by Peardian** [comment]
As I said, yes. I highly suggest reading the documentation in each class, as it describes what the class can do and may answer other questions you have.
