### ISSUE TITLE
How do i get order report of last 24 hours

### ISSUE THREAD

**Issue by harshitnayak45** [CPIGroup/phpAmazonMWS#126]
Do we have any example regarding order report. I need to fetch the order report for last 24 hours. Please post example here.

**Comment by harshitnayak45** [comment]
My mistake it has closed but i need a example for this.

**Comment by harshitnayak45** [comment]
I have got report id and fetch report as well. But how can i get order details? Please let me know asap.

**Comment by harshitnayak45** [comment]
I have retrieve a report request id with in start date and end date . How do i get the report id from that. I need to store single csv from two given dates that have all the records. no need to have multiple reports.

**Comment by Peardian** [comment]
To get order details, you need to use the Orders API, as I think the detailed information you are looking for is not available in the reports. I might be wrong, as I am not familiar with all of Amazon's report types. I don't think Amazon will have a way to get exactly the information you need in the format you desire.

For your other questions, please read the documentation I have provided for each class. It includes information on how to use the classes to accomplish specific tasks and should hopefully answer some of your questions.

**Comment by Peardian** [comment]
I am going to assume that the question has been answered.
