### ISSUE TITLE
Method for finance event report

### ISSUE THREAD

**Issue by lrjbrual** [CPIGroup/phpAmazonMWS#127]
Dear Team, 

I would like to seek your assistance if we have a financial event for SAFETReimbursementEventList here's the link: [http://docs.developer.amazonservices.com/en_UK/finances/Finances_Datatypes.html#FinancialEventGroup](url)
As per checking on the AmazonFinancialEvents.php file we don't have the SAFETReimbursementEventList. if anyone created the events please do let us know, since my team are now working on it. to include in our web app. 

Thank you :)

**Comment by Peardian** [comment]
It seems Amazon recently added this to the API, so thanks for bringing it to my attention. I myself haven't done anything yet regarding this new feature, though I can't speak for any of the other users who have forked the library.

**Comment by lrjbrual** [comment]
We already coded this just today @Peardian we will share our codes once it is working. now we still validating on it.  cheers!

**Comment by Peardian** [comment]
Support for SAFE-T Reimbursement events has been added to the master dev branch!
