### ISSUE TITLE
Secret key is not working

### ISSUE THREAD

**Issue by Alexandre33310** [CPIGroup/phpAmazonMWS#131]
Hello,

I have complete the amazon-config.php file with the following amazon mws account settings : 
 - merchantId
 - marketplaceId
 - keyId
 - secretKey

Unfortunately, the order_examples.php file show me the following error : There was a problem with the Amazon library. Error: Secret Key is missing!

The secret key is well completed in the amazon-config.php file.

I have look at the log.txt file and I have the following error : 
[Warning][2017/06/28 18:10:23 guest@XXX.XX.XX.X AmazonCore.php:133 setStore] Store MyStore_Well_ Completed does not exist!
[Urgent][2017/06/28 18:10:23 guest@XXX.XX.XX.X AmazonOrderList.php:50 resetMarketplaceFilter] Marketplace ID is missing

How can I fix the issue ?

**Comment by Peardian** [comment]
Did you make sure that the store name you provided to the object matches the array key in the store array? Be sure to read all of the comments in the example files and the readme for more information.

**Comment by Alexandre33310** [comment]
Thank you very much !
My mistake was ridiculous, i didn't replace 'YourAmazonStore' by 'MyStoreName' in the file amazon-config.php for the following variables : 
$store['YourAmazonStore']['merchantId']
$store['YourAmazonStore']['marketplaceId']
$store['YourAmazonStore']['keyId']
$store['YourAmazonStore']['secretKey']
$store['YourAmazonStore']['serviceUrl']
$store['YourAmazonStore']['MWSAuthToken']

Thank you very much for your help.
