### ISSUE TITLE
Multiple MarketplaceId's in AmazonOrderList class

### ISSUE THREAD

**Issue by Doublemedia** [CPIGroup/phpAmazonMWS#133]
Hi!

In the AmazonFeed class i can use: "setMarketplaceIds" to set multiple marketplaces.
I cant find this function for the AmazonOrderList class.

Is there a way to get my orders of all marketplace instead of only default (Germany)?

Raymond

**Comment by Peardian** [comment]
The Order List class has `setMarketplaceFilter` instead, which was added in the most recent release. If you are using an older version, I recommend updating.

**Comment by Doublemedia** [comment]
Thank @Peardian. Found it :)

@ all, just put this for EU marketplaces:
[        $amazon->setMarketplaceFilter(
            array(
                'A1PA6795UKMFR9',
                'A1RKKUPIHCS9HS',
                'A13V1IB3VIYZZH',
                'APJ6JRA9NG5V4',
                'A1F83G8C2ARO7P'
            )
        );]

**Comment by Peardian** [comment]
Glad to hear it. I recommend reading through the function documentation in each class in case there are other features in there that you find useful.
