### ISSUE TITLE
hi use MarketplaceWebService_Model_SubmitFeedRequest 

### ISSUE THREAD

**Issue by viyongyong** [CPIGroup/phpAmazonMWS#135]
post _POST_FBA_INBOUND_CARTON_CONTENTS_

result 
Merchant ID provided in feed does not match Merchant ID used to generate the request. (FBA_INBOUND_CARTON_004)

**Comment by Peardian** [comment]
It sounds like you are using a different library to make the request. Even though I cannot help you with the library, I can at least help out by saying the problem seems to be with the contents of your feed. I cannot help you any more than that.

**Comment by viyongyong** [comment]
Thanks for your reply.
Only one submit feed, then result feed msg FBA_INBOUND_CARTON_004
