### ISSUE TITLE
Hourly request quota Product Api

### ISSUE THREAD

**Issue by bado57** [CPIGroup/phpAmazonMWS#141]
Hi, I've been looking into this a lot, but I do not understand. Please tell me how many products I can get the maximum minimum price per hour. How many products can I find in the maximum minimum price per minute.

http://docs.developer.amazonservices.com/en_US/products/Products_GetCompetitivePricingForSKU.html

**Comment by Peardian** [comment]
If the "Hourly request quota" is 36000 requests per hour, and each request contains no more than 20 items, it would seem that the answer is 36000 &times; 20 = 720000 items per hour.

However, the answer is not really that straightforward. If the restore rate is 10 items per second, that would mean you could make no more than one request per second for only 10 items each after the initial quota is reached.

Assuming that you start the hour with a fresh slate, you get a total of (20 &times; 20) + (59 &times; 10) = 990 items per hour maximum. If you start the hour already throttled, you only get 60 &times; 10 = 600 items per hour.

**Comment by bado57** [comment]
there is a way to increase?

**Comment by Peardian** [comment]
You would have to ask Amazon about that, because I have no idea. The documentation seems to imply that these are limits that apply to everyone equally, not on a per-account basis.

**Comment by bado57** [comment]
Thank you. Have a great day!
