### ISSUE TITLE
How to use this when the SellerId and auth token is available in the config

### ISSUE THREAD

**Issue by luigel** [CPIGroup/phpAmazonMWS#145]
It is requiring me to input the access key and secret key in the config. Is it possible to edit it that it will require only the MWS Auth Token, and SellerId? Thanks

**Comment by Peardian** [comment]
The key is used to generate the hash signature that goes with the request, so I don't know if you can go without it completely. I don't know enough about how the MWS Auth Token is used.

**Comment by luigel** [comment]
Thank you. And I really need to test it on how it works. Thanks. Good day!
