### ISSUE TITLE
multiple marketplaces & reports

### ISSUE THREAD

**Issue by KarelVanLandschoot** [CPIGroup/phpAmazonMWS#152]
Hi, 

I am using Amazon to sell goods on amazon.de and amazon.fr.
But with phpamazonmws it seems like I'm overseeing something.
The goal is to get 2 inventory reports (one from DE and one from FR)
but when I perform a call, for some reason each call is handled by the DE.

first my calls: 
`$content=getAmazonReportRequest('_GET_MERCHANT_LISTINGS_DATA_','myStoreFR');`
OR 
`$content=getAmazonReportRequest('_GET_MERCHANT_LISTINGS_DATA_','myStoreDE');`

below is what my config looks like:
```$store['myStoreDE']['merchantId'] = 'A2ORS6ID4B81V6';//Merchant ID for this store
$store['myStoreDE']['merchantId'] = 'A2ORS6ID4B81V6';//Merchant ID for this store
$store['myStoreDE']['marketplaceId'] = 'A1PA6795UKMFR9'; //Marketplace ID for this store
$store['myStoreDE']['keyId'] = '{MYKEY}'; //Access Key ID
$store['myStoreDE']['secretKey'] = '{MYSECRET}'; //Secret Access Key for this store
$store['myStoreDE']['serviceUrl'] = ''; //optional override for Service URL
$store['myStoreDE']['MWSAuthToken'] = ''; //token needed for web apps and third-party developers
 
$store['myStoreFR']['merchantId'] = 'A2ORS6ID4B81V6';//Merchant ID for this store
$store['myStoreFR']['marketplaceId'] = 'A13V1IB3VIYZZH'; //Marketplace ID for this store
$store['myStoreFR']['keyId'] = '{MYKEY}'; //Access Key ID
$store['myStoreFR']['secretKey'] = '{MYSECRET}'; //Secret Access Key for this store
$store['myStoreFR']['serviceUrl'] = ''; //optional override for Service URL
$store['myStoreFR']['MWSAuthToken'] = ''; //token needed for web apps and third-party developers
```

and finally my function: 
```
function getAmazonReportRequest($type,$marketplace) {
    try {
        $obj = new AmazonReportRequest($marketplace); //store name matches the array key in the config file
        //$obj->setUseToken(); //tells the object to automatically use tokens right away
        $obj->setReportType($type);
        $obj->requestReport(); //this is what actually sends the request
        return $obj->getResponse();
    } catch (Exception $ex) {
        echo 'There was a problem with the Amazon library. Error: '.$ex->getMessage();
    }   
}
```

Both of my call are generating ID's, but both of them are in my DE-account when i look in the seller.amazon.de ->select amazon.de -> inventory -> inventory reports
the page seller.amazon.de ->select amazon.fr -> inventory -> inventory reports is blank.

Hope you can figure out something?
I do find it bizar that the config array looks very similar, the only parameter changes it marketplace. correct?

**Comment by Peardian** [comment]
The code you have should work as far as I can tell. As long as you have the correct Merchant IDs and keys in their respective store arrays, the request should be made with that corresponding store.

In the function that requests the report, try dumping the object's options (`->getOptions()`) after making the requesting to verify that the store credentials correctly belong to the store. (You don't need to show me, just check them yourself.)

I am not very familiar with how Amazon handles stores that operate in multiple marketplaces, so it is possible that Amazon is doing something behind the scenes. According to the [documentation](http://docs.developer.amazonservices.com/en_US/reports/Reports_RequestReport.html), a single report can encompass multiple marketplaces. They also have a [page that explains about using multiple marketplaces](http://docs.developer.amazonservices.com/en_US/reports/Reports_UsingMultipleMarketplaces.html), which may be helpful.

**Comment by KarelVanLandschoot** [comment]
Hi Peardian, 
I used getOptions() to ouput the data, but actually there is no changes in a call to myStoreFR or myStoreDE. Both output is the same, the only thing that changes is the signature, (but that changes every request anyway).
I see in AmazonCore.php that the config ['keyId'] will be translated in [AWSAccessKeyId]. For both of my marketplaces I used the same key. could this be wrong? The array credentials in config of both sites are identically, except the marketplaceId is diffrent. Is this correct? I could not find any answer on that yet.

**Comment by Peardian** [comment]
Unfortunately, I don't know if that is correct or not, since I have very little experience with the business side of Amazon MWS. These would be questions to ask Amazon. Ensuring that the library properly sends your credentials is as far as I can help you.

**Comment by Peardian** [comment]
Since it has been nearly two months without any follow-up, I am assuming that the issue has been addressed.
