### ISSUE TITLE
MalformedInput - timestamp must follow ISO8601

### ISSUE THREAD

**Issue by JonLaliberte** [CPIGroup/phpAmazonMWS#153]
I've had this code running in production for at least a year. Just today I started getting errors: from AmazonOrderList.php checkResponse: `Bad Response! 400 Bad Request: MalformedInput - timestamp must follow ISO8601`

I'm calling `fetchOrders` having already used `$amz->setLimits('Modified', "-1 weeks");`

No other changes were made to the code or configuration any time recently.

I added some logging to genTime and the results are as expected (they are proper ISO 8601 format).
Any idea what could be happening?

**Comment by joe-pritchard** [comment]
This started happening to me today with GetOrders  as well, but interestingly only in Japan... No changes have been made to the date format whatsoever and I've done no updates. I'm assuming Amazon have changed something, but not in Europe and North America... Are you seeing the issue in other regions?

**Comment by JonLaliberte** [comment]
I'm actually seeing it only in North America.

**Comment by JonLaliberte** [comment]
I think I've got it fixed.

In AmazonCore.php, the `genTime` function returns `date('Y-m-d\TH:i:sO',$time-120)`. 
It should instead be returning either `date('Y-m-d\TH:i:sP',$time-120)` or `date('c',$time-120)`

**Comment by tobiasdalhof** [comment]
Same issue here (Amazon Germany). 
Using Laravel Fork https://github.com/sonnenglas/amazon-mws-laravel/

**Comment by joe-pritchard** [comment]
Confirming this has fixed it! After some time the issue started affecting me in all regions too, not sure why it was only Japan for a while... @JonLaliberte , I have a fork with this fix in it, would you like to submit a PR to the main repo? If not I'll happily send mine...

**Comment by JonLaliberte** [comment]
@joe-pritchard Sure, go ahead and submit, I won't have time to do it for a bit (my repo has a few other customizations). Over on the MWS forums it looks like Amazon may have changed something too, some are reporting that the issue stopped affecting them without any code changes. No matter, I believe the change we've made is the format Amazon expects so it would be a good change to have.

**Comment by Peardian** [comment]
@JonLaliberte The store that I work with started having this same problem, too, and it's still ongoing. Thank you for reporting it and for finding a solution for it. I'll work on getting this fixed and released within the next few days.

**Comment by Peardian** [comment]
The bug fix is now in place as **Version 1.4.2**! Thanks again for helping with this problem.
