### ISSUE TITLE
Check if a product exists already

### ISSUE THREAD

**Issue by ciolo** [CPIGroup/phpAmazonMWS#154]
Hi,
this repo help me a lot. Thank u. 
However, I have a question: is there the function to check if a products exists on Amazon Marketplace (thats is, a function called "ListMatchingProducts")?

**Comment by ciolo** [comment]
Sorry, I found it now. What is the function to return or print the result of query?
Thank u.

**Comment by Peardian** [comment]
The documentation for the `searchProducts()` method indicates that you can use `getProduct()` to retrieve the information returned from Amazon.

I recommend reading the documentation for each class/function, as I put a lot of helpful information into them.

**Comment by simplyrahul** [comment]
When you say documentation, do you mean the comments in class files?

**Comment by Peardian** [comment]
Yes, that is what I mean. The comments in each class are standard phpDocumentor comments.

**Comment by Peardian** [comment]
Seems like I can close this now.
