### ISSUE TITLE
Retrieve price from InventoryList

### ISSUE THREAD

**Issue by ciolo** [CPIGroup/phpAmazonMWS#158]
Hi,
I've read the documentation for Inventory, but i didn't find it. Is it possible retrieve price to products in my marketplace as you did for quantity?

**Comment by Peardian** [comment]
An item's price is not an attribute of your inventory, but of the product's listing itself. If you search around in the `AmazonProductInfo` class, you will find several methods for retrieving price information.

**Comment by Peardian** [comment]
It has been three weeks with no response, so I am assuming the question has been answered.
