### ISSUE TITLE
please help AmazonReportRequest no response.

### ISSUE THREAD

**Issue by buddyy93** [CPIGroup/phpAmazonMWS#161]
public function index()
    {
        try {
            $amz = new AmazonReportRequest("sales_planet");
            $amz->setReportType('_GET_MERCHANT_LISTINGS_DATA_'); //exclude cancelled feeds
            $amz->setTimeLimits('2018-08-01','2018-08-02');
            $amz->setMarketplaces("mymarketplaceid");
            $amz->requestReport();
            print_r($amz->getResponse());
        } catch (Exception $ex) {
            echo 'There was a problem with the Amazon library. Error: ' . $ex->getMessage();
        }
    }

my config

$store['sales_planet']['merchantId'] = 'id';//Merchant ID for this store
$store['sales_planet']['marketplaceId'] = 'id'; //Marketplace ID for this store
$store['sales_planet']['keyId'] = 'keyid'; //Access Key ID
$store['sales_planet']['secretKey'] = 'secretkey'; //Secret Access Key for this store
$store['sales_planet']['serviceUrl'] = ''; //optional override for Service URL
$store['sales_planet']['MWSAuthToken'] = ''; //token needed for web apps and third-party developers

$AMAZON_SERVICE_URL = 'https://mws.amazonservices.com/';

please help, i keep getting no response on every request, thank you in advance

**Comment by Peardian** [comment]
The code you have written here seems fine. Did you check the log? Does it say whether or not a request is being sent?

**Comment by buddyy93** [comment]
@Peardian i found out that it's because i'm running it on localhost, after i do $obj->setDisableSslVerify(true), everything worked out, thank you
