### ISSUE TITLE
how can i format the returned report into associative array?

### ISSUE THREAD

**Issue by buddyy93** [CPIGroup/phpAmazonMWS#162]
so i have succesfully got the report data, but it's kinda in string i want it to be an associative array, the return is as follows.

item-name	item-description	listing-id	seller-sku	price	quantity	open-date	image-url	item-is-marketplace	product-id-type	zshop-shipping-fee	item-note	item-condition	zshop-category1	zshop-browse-path	zshop-storefront-feature	asin1	asin2	asin3	will-ship-internationally	expedited-shipping	zshop-boldface	product-id	bid-for-featured-placement	add-delete	pending-quantity	fulfillment-channel	merchant-shipping-group
Better Homes and Gardens Old World Arabic Wall Clock		0802UW0V0P9	CLOCK1	28.99	1	2018-08-01 23:50:12 PDT		y	1			11				B009ZH58TW						B009ZH58TW			0	DEFAULT	Migrated Template
Pyrex Simply Store 12-pc Set Glass Food Storage with Multi-colored Lids		0802UVWA6DG	USWL-16561608	37.5	2	2018-08-01 23:43:18 PDT		y	1			11				B06XHRB6GZ						B06XHRB6GZ			0	DEFAULT	Migrated Template
Wall Clock Blue Neon 11" Glass Lens Plastic Frame Battery Operated Retro Style Teens Bedroom Decor		0802UVZD497	Clock2	44.99	0	2018-08-01 23:51:40 PDT		y	1			11				B0752T9T77						B0752T9T77			0	DEFAULT	Migrated Template

can somebody tell me how i can format it into an associative array? thank you in advance.

**Comment by Peardian** [comment]
Sorry, this library does nothing to parse or change the CSV/XML reports provided by Amazon.
