### ISSUE TITLE
Why the delivery date is incorrect.

### ISSUE THREAD

**Issue by nbcxyk** [CPIGroup/phpAmazonMWS#163]
There are problem for AmazonFulfillmentOrderCreator.php
Wh[SellerFulfillmentOrderId] => H730322525818885-10 [DisplayableOrderId] => H730322525818885-10 [DisplayableOrderDateTime] => 2018-08-07T08:50:35+08:00 [DisplayableOrderComment] => Thanks for your order [ShippingSpeedCategory] => Standard [NotificationEmailList.member.1] => **8@ddasdf.com [FulfillmentAction] => Ship [FulfillmentPolicy] => FillOrKill.....
----------
Why the Estimated Delivery Date for This Item: 7 September 2018 

Who can help me to check it . Thanks.

**Comment by Peardian** [comment]
Unless I am mistaken, that date says _August_.

According to the Amazon documentation, the DisplayableOrderDateTime is specified by the person who submitted the request to create the order. Unless you have proof that a different date was submitted with the create request, this issue has nothing to do with this library.

**Comment by nbcxyk** [comment]
Hi you can find the problem in the attachment. Thanks.

**Comment by Peardian** [comment]
I don't see any attachments. Try uploading it through the GitHub page instead of using email.
