### ISSUE TITLE
AmazonReport   class return raw text.

### ISSUE THREAD

**Issue by Gurpreet68** [CPIGroup/phpAmazonMWS#170]
AmazonReport  return text in paragraphs, but I want it in object/array. Can you please let me know why it is happening? 
https://github.com/CPIGroup/phpAmazonMWS/blob/stable/includes/classes/AmazonReport.php

where code is "rawreport"   it creates raw text from response.

**Comment by Peardian** [comment]
You can find the answer to your question here: https://github.com/CPIGroup/phpAmazonMWS/issues/110

**Comment by Peardian** [comment]
It seems the answer provided was enough to solve the problem, so I'm going to close this now.
