### ISSUE TITLE
Title with quotes came messy

### ISSUE THREAD

**Issue by slumdogbi** [CPIGroup/phpAmazonMWS#172]
Generating a health report one product that has quotes on the title comes without the quotes (comes with this �). Probably some problem with encoding but can't find how to fix it. What I did:

1. Check php.ini charset. Was set to UTF-8
2. Check response from Amazon using scratchpad. The quotes appears normally
3. Trying to convert the text after the report with mb_convert_encoding($text, "UTF-8") but the quotes is substituted with "?"

Don't know what else to do, a little help will be very appreciated.

Thanks

**Comment by Peardian** [comment]
I'm afraid I have very little experience with character encoding, so I don't know what the problem would be.  Reports are fetched using standard cURL and given raw. Unless there is some kind of cURL setting that the library needs to support, there is not much else I can do to help.

**Comment by slumdogbi** [comment]
Thanks for replying. Two days looking into it and did't find a solution yet. I tried to run in another environment (I was running on Mac OS X), Linux 16.04 fresh install but I got the exact same error. I will just remove any reference of this using "UTF-8//IGNORE//TRANSLIT". At least I don't get invalid character error. Thanks again.

**Comment by Peardian** [comment]
I think I can safely close this now .
