### ISSUE TITLE
AmazonOrderList.php:428 checkResponse] No Response found

### ISSUE THREAD

**Issue by ulast** [CPIGroup/phpAmazonMWS#177]
My config file ;
`$store['YourAmazonStore']['merchantId']         = '***********';//Merchant ID for this store
$store['YourAmazonStore']['marketplaceId']      = 'A33AVAJ2PDY3EV'; //Marketplace ID for this store
$store['YourAmazonStore']['keyId']              = '****************'; //Access Key ID
$store['YourAmazonStore']['secretKey']          = '*******************'; //Secret Access Key for this store
$store['YourAmazonStore']['serviceUrl']         = ''; //optional override for Service URL
$store['YourAmazonStore']['MWSAuthToken']       = 'amzn.mws.*****-*****-****-****-*******'; `

Service Url ;
`$AMAZON_SERVICE_URL = 'https://mws-eu.amazonservices.com/';`

Warning Log ;
`[Warning][2019/03/11 12:47:53 guest@::1 AmazonOrderList.php:428 checkResponse] No Response found`

Help me pls.

**Comment by Peardian** [comment]
This could possibly be an issue with your config, but there could also be other issues unrelated to the library. Try dumping the object and look for the property **urlbase**. If urlbase is set to your desired Amazon service URL, then there is not much else I can do to help.

**Comment by Peardian** [comment]
It has been over a month with no reply, so I'm guessing the problem was solved somehow. I will close this now.
