### ISSUE TITLE
Feeds SubmitFeed now require Content-Type header

### ISSUE THREAD

**Issue by venditiogroup** [CPIGroup/phpAmazonMWS#179]
Starting late 04/30/2019 we started getting errors on feeds submitted with this library. We received the error "keys may not contain &lt;". I found a post on sellercentral forums where other API users were receiving the same error.

It seems Amazon started requiring the Content-Type header be sent for feed submission request. As we're only sending XML feeds, I added the header 'Content-Type: text/xml' and feed submissions starting working again.

**Comment by Peardian** [comment]
Interesting, I will have to look into this more. It certainly seems to be affecting multiple people, as someone else created a pull request on the same subject, but the company I work with has not had any issues yet. Thank you for bringing this issue to my attention.

**Comment by Peardian** [comment]
A few minutes ago, an Amazon rep replied to the thread I linked to:

> Hi,
>
> Thank you for the feed back and solution. We have switched back the rule that requires content-type and your requests should be successful now.
>
> We will post an announcement if content-type is required. Sorry for the inconvenience caused.

Still, it seems like the library needs to be updated to prevent this from happening again in the future.

**Comment by Peardian** [comment]
My solution may not be ideal for users in China or Japan, but it should prevent any future issues for everyone else. Thanks again for reporting this.

**Comment by pgbrown** [comment]
This problem was occurring for me since yesterday around 5:30am UTC (Amazon Australia). I implemented your solution and the Feeds were successfully submitted.

**Comment by Peardian** [comment]
Thanks for letting me know. The same thing happened for the company I work for. So much for Amazon giving us a warning.

**Comment by SimonDing87** [comment]
Thank you for announcing this solution!  My company had this issue as well, and sending a header of "Content-Type: text/xml" resolved this for us.
