### ISSUE TITLE
How to apply for mws developer ID?

### ISSUE THREAD

**Issue by willianwong** [CPIGroup/phpAmazonMWS#181]
Have you applied for the mws developer ID recently?
After I applied, I waited for 40 days, Amazon told me that I was not qualified, and told me that I needed to learn Acceptable Use Policy and Data Protection Policy.

Can you provide help?
thank you very much!

**Comment by Peardian** [comment]
Sorry, I can't help you with that. Besides, this question isn't really about the library anyway.
