### ISSUE TITLE
question: inventory_example

### ISSUE THREAD

**Issue by rickoneeleven** [CPIGroup/phpAmazonMWS#32]
https://github.com/CPIGroup/phpAmazonMWS/blob/stable/examples/inventory_examples.php

Hi

Thanks, I've managed to pull orders, and update shipping with your api, thanks very much. I am having issues getting my inventory though. I've followed the tutorial but return $obj->getSupply(); is null.

I've even tried putting in a sleep command and get getSupply a little later but it's always null. Any ideas?

Thanks
(I've filled in my store and can confirm that's all working as I pull order status a stuff down using your API)

Cheers
R

**Comment by serchie** [comment]
I'm having the same issue, order_examples works like a charm (thank you for this) but I get a blank page when execute inventory_examples.

I can't manage to see getLastResponse() method output (I'm completely know-nothing in php dev).

Shall somebody paste a little example?

Thank you in advance.
