### ISSUE TITLE
No relationship returns of GetMatchingProductForId with parent product asin.

### ISSUE THREAD

**Issue by ruiwant** [CPIGroup/phpAmazonMWS#35]
There is no relationship returns when I use the GetMatchingProductForId method with a parent product asin, but ok with a child product asin.

The Amazon MWS Scratchpad returns the relationship while i use parent or child product asin. Is it a bug or something i need to do.

Thank you very much.

**Comment by Peardian** [comment]
I found the cause of the bug: Amazon uses a namespace when giving child variation data, but not when giving parent variation data. Now the product checks all children both with and without a namespace. Thanks again for reporting this.
