### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by btray77** [CPIGroup/phpAmazonMWS#40]
How would I use the GetProductCategoriesForASIN properly?

I've tried 3 different methods.  the last one works, but is very inefficient.  
```
<?php
require('./amazon-mws/includes/classes.php'); 
```
#1 
```
$amz = new AmazonProductInfo();
$listofASIN = array('B00V86GJN2' ,'B00I1K876K','B00B1ULXG8','B00OY6WGV2','B003NHFEDU');
$amz->setASINs($listofASIN);
$amz->fetchCategories();
$products = $amz->getProduct();
foreach ($products as $p) {
	$p = $p->getData();
	echo $p['Categories'][0]['ProductCategoryId'] . PHP_EOL;
}
// Above only returns 1 product
```
#2 
```
foreach ($listofASIN as $asin)
{
	$amz->setASINs($asin);
$amz->fetchCategories();
$products = $amz->getProduct();
foreach ($products as $p) {
	$p = $p->getData();
	echo $p['Categories'][0]['ProductCategoryId'] . PHP_EOL;
}

}
// Above returns 15 CategoryId's because it adds items to the Data every iteration.  
```

#3 
```
foreach ($listofASIN as $asin)
{
	$amz = new AmazonProductInfo();
	$amz->setASINs($asin);
$amz->fetchCategories();
$products = $amz->getProduct();
foreach ($products as $p) {
	$p = $p->getData();
	echo $p['Categories'][0]['ProductCategoryId'] . PHP_EOL;
}

} // Inefficient creating a new AmazonProductInfo object every time.

```
Thanks

**Comment by Peardian** [comment]
Unfortunately, the `GetProductCategoriesForASIN` (and `GetProductCategoriesForSKU`) actions only works for one product at a time.

The third example is the most correct way of doing it, as the objects are not designed to be reused for requests like in the second example. In this particular case, however, you could get away with using a combination of the second and third examples. Each time you make a request with the object, the product is added to end of the list, so the only actions that you really have to loop through are `setASINs` and `fetchCategories`. After that, you only need to call `getProduct` once.

**Comment by Peardian** [comment]
No response in a week, so I will assume the answer I gave was satisfactory.
