### ISSUE TITLE
Orders Items

### ISSUE THREAD

**Issue by stevukas** [CPIGroup/phpAmazonMWS#41]
Hello, thanks for the great SDK, i just have one question please, how to get orders list with their items
I need Orders Items to be included in Orders array list.

**Comment by Peardian** [comment]
Unfortunately, order items must be retrieved separately from the orders themselves. Once you have the orders you want, use each order object's `fetchItems` method to get the items.

**Comment by stevukas** [comment]
Thank you for your quick response, i just figured it out
