### ISSUE TITLE
AmazonReport uses private variables, limiting possiblities to extend

### ISSUE THREAD

**Issue by ThomasRedstone** [CPIGroup/phpAmazonMWS#50]
I doubt it's the only place private variables are used, but in my case I want to save the report to a variable, and not to a file, and then manipulate it, but as it stands I can't extend and access the $rawReport variable.
In general, it would be useful for most private variables to be made protected instead, to allow users to extend to fit their own use cases.

**Comment by Peardian** [comment]
That's a good point. When I first wrote the class, the only requirement I had was that it could save to a file, so I didn't even think to add a getter for the raw data.

I'll work on improving it when I am able to. I want to put some thought into whether or not to make the variables protected, but at the very least I want to add a getter for the data.

**Comment by Peardian** [comment]
Taken care of.

**Comment by ThomasRedstone** [comment]
Superb! Thank you :-)
I'm just coming to use the library for a whole new project, and it looks like it's had some great improvements since I last used it!
Great work!
