### ISSUE TITLE
AmazonProduct won't parse all SalesRankings

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#52]
I wanted to validate that my changes in #51 wouldn't break the existing code, I started writing a testcase where I validate the `fetchProductList.xml` file. 

Analysing this piece of that Xml file:
```xml
<SalesRankings>
    <SalesRank>
        <ProductCategoryId>book_display_on_website</ProductCategoryId>
        <Rank>53138</Rank>
    </SalesRank>
    <SalesRank>
        <ProductCategoryId>377886011</ProductCategoryId>
        <Rank>56</Rank>
    </SalesRank>
</SalesRankings>
```
It should be that there are 2 SalesRanking entries in the AmazonProduct object. But the code contains the same error the #51 bug has. The loops overwrite the value:
```php
//SalesRankings
if ($xml->SalesRankings){
    foreach($xml->SalesRankings->children() as $x){
        foreach($x->children() as $y){
            $this->data['SalesRankings'][$x->getName()][$y->getName()] = (string)$y;
        }
    }
}
```
Running the code gives this output:
```php
[SalesRankings] => Array
(
    [SalesRank] => Array
    (
        [ProductCategoryId] => 377886011
        [Rank] => 56
    )
)
```
Where it should have been:
```php
[SalesRankings] => Array
(
    [0] => Array
    (
        [ProductCategoryId] => book_display_on_website
        [Rank] => 53138
    )
    [1] => Array
    (
        [ProductCategoryId] => 377886011
        [Rank] => 56
    )
)
```
Supposed fix
```php
//SalesRankings
if ($xml->SalesRankings){
    foreach($xml->SalesRankings->children() as $child){
        $this->data['SalesRankings'][] = (array) $child;
    }
}
```

**Comment by Peardian** [comment]
It is strange that this is not working, because I wrote a script for getting this information and didn't notice any problems with it. Once I have the time to work on the library again, this will be the first thing I investigate. Thanks for finding this.

**Comment by Peardian** [comment]
Taken care of
