### ISSUE TITLE
Unable to see to what Id - IdType combination a AmazonProduct belongs to

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#53]
For my application I want to add products at Amazon. After the whole process I want to fetch the ASIN's that map to my SellerSku's. For that I want to use the AmazonProductList class (getProductById). After executing the query I get my results (for 5 products including variations) from Amazon, but I'm unable to relate to what product they belong because the Id and IdType values are not stored in the AmazonProduct. It's simply impossible to tell to what SellerSku, EAN or ISBN the results belong. 

There for I want to suggest these changes in the `AmazonProductCore` class for function `parseXML($xml)`, at line 93:

```php
$this->productList[$this->index]->data['Identifiers'] = array_merge($this->productList[$this->index]->data['Identifiers'], ['Request' => $temp['@attributes']]);
```

This will inject the Id and IdType of the Product that was searched for. Sample:

```php
AmazonProduct Object
(
    [data:protected] => Array
    (
        [Identifiers] => Array
        (
            [MarketplaceASIN] => Array
            (
                [MarketplaceId] => A1PA6795UKMFR9
                [ASIN] => B00V38Q1DI
            )
            [Request] => Array
            (
                [Id] => 8718888013105
                [IdType] => EAN
                [status] => Success
            )
        )
    )
)
```

**Comment by Peardian** [comment]
That seems like a useful change. I will look into it when I have the time.

**Comment by Peardian** [comment]
I implemented your suggestion. Thanks!
