### ISSUE TITLE
Fetch OrderReport

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#54]
I have been looking inside the source code, but it seems you do not have the option to fetch an OrderReport. It is possible to let the Seller Central generate an OrderReport at a certain interval. The [documentation](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf) also states the use of OrderReport and not the OrderList. Although you could do it with both, some users [advise](http://stackoverflow.com/questions/27427264/amazon-mws-difference-between-reports-and-order-lists) to use the OrderReport. 

Looking forward to your thoughts about this.

**Comment by Peardian** [comment]
I know of the Reports API, which has some Order-related reports, but I have never heard of anything specifically called "OrderReport". This must be a new feature that was added within the past year. It sounds very useful, though it may have to wait until the next version.

**Comment by HMAZonderland** [comment]
It was added later on. I'll add this feature in my fork.

**Comment by Peardian** [comment]
I have finally had a chance to look into it. It seems this is a type of Report that you set up to be generated regularly using the `AmazonReportScheduleManager`.

**Comment by HMAZonderland** [comment]
Are you not going to implement this API? Unfortunately I was unable to do so.

**Comment by Peardian** [comment]
As far as I am aware, the order report is a regular report that can be retrieved the same way that other reports are retrieved, which is something that is already supported.
