### ISSUE TITLE
Unable to specify MWSAuthToken

### ISSUE THREAD

**Issue by efCode** [CPIGroup/phpAmazonMWS#56]
Hi,

This looks like a fantastic library, however on usage i can't seem to specify or set MWSAuthToken. 
Is this available ?

**Comment by Peardian** [comment]
I was completely unaware of this feature, but it seems like an important one to have. It should definitely be added in the next version. Unfortunately, I am unable to do anything about it myself at this time.

Thank you for bringing this missing feature to my attention.

**Comment by zoro16** [comment]
Hi,
First of all thanks a lot for the great effort and for sharing.

Can you please tell us where can we add "MWSAuthToken"? In the AmazonClient they add it into "parameters[] " array, in your code is "options[]" or "param[]" i'm not sure?

**Comment by Peardian** [comment]
If MWSAuthToken is a standard parameter like SellerId, then it should go in `$this->options[]`, yes. I have not yet been able to look into this issue, so I may be wrong on this.

**Comment by Peardian** [comment]
Support for the MWSAuthToken has been added to the master branch and will be part of the next release.

**Comment by zoro16** [comment]
Thanks a lot Peardian. when is the next release, if i may ask :)

**Comment by Peardian** [comment]
There is no specific date for the release, just whenever I finish getting all of the classes up to date with the current documentation and adding support for the new APIs.
