### ISSUE TITLE
ListOrder url bug

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#57]
Found a bug where the url for ListOrders is not created correctly. I fixed this in my own repository. Fix could also be made in the `fetchOrders` function in the `AmazonOrderList` class. Possible fix could also be:

```php
public function fetchOrders($r = true){
    [..]
    
    $url = $this->urlbase.'/'.$this->urlbranch;
    
    $query = $this->genQuery();
    
    $path = $this->options['Action'].'Result';
    [..]
}
```

My fix:
https://github.com/HMAZonderland/phpAmazonMWS/commit/bb9cf78e715b55ac5e4a1b28538f9ea50cd35e61

**Comment by HMAZonderland** [comment]
My bad. Forgot that the url is set in the config and should include the tailing slash.

**Comment by Peardian** [comment]
Sounds like the issue is already resolved.

At some point in the future, I want to improve the config code so that the URL works whether or not the ending slash is included in the config file.

**Comment by Peardian** [comment]
Added a feature to the master branch so that the URL will work with or without the slash at the end.
