### ISSUE TITLE
What is this supposed to do?

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#58]
AmazonCore line 800.

```php
/**
 * Reformats the provided string using rawurlencode while also replacing ~, copied from Amazon
 *
 * Almost the same as using rawurlencode
 * @param string $value
 * @return string
 */
protected function _urlencode($value)
{
    return rawurlencode($value);
    return str_replace('%7E', '~', rawurlencode($value));
}
```

**Comment by Peardian** [comment]
It replaces any tilde in the URL with its encoded version. I don't remember the exact reason off the top of my head, but I don't think Amazon allows tildes in the request URLs.

**Comment by HMAZonderland** [comment]
But the second return can never be reached. I'm doing some updating on my code base, and my IDE pointed out this function. Do you want to drop the `str_replace` function?

**Comment by Peardian** [comment]
Oh, you're right, I didn't notice that, sorry.

I don't remember the reasoning for why I did that. It might have been something the API documentation mentioned that turned out to be incorrect. Either way, if it's working fine with tildes now, then I guess that second line can be removed.

**Comment by Peardian** [comment]
I disabled the line but left it in place with a comment stating that the line came from Amazon. If I ever find that their code has changed to not replace tildes, I will remove the line completely.
