### ISSUE TITLE
How to bulk create products at amazon via this API

### ISSUE THREAD

**Issue by raheelkhan** [CPIGroup/phpAmazonMWS#59]
I am just exploring your API and thank you for combining all these stuffs together. But due to no documentation i am unable to identify which class should i use and from where i see the methods.

For example i want to do a bulk creation of products via this API
Also i want to convert my normal products to FBA.

Please provide me sample for that so that i can follow along.

Thanks

**Comment by Peardian** [comment]
Product creation and manipulation like the kind you mentioned are handled by feeds, which are independent of the Amazon MWS API. The Amazon website has documentation and templates that you can use for creating feed files, though it might take for a while to find them.

Once you have created your feed files, however, you can use an `AmazonFeed` object to send your feed, an `AmazonFeedResult` object to see how the feed was processed, and an `AmazonProductList` object to verify that your products were created.
