### ISSUE TITLE
ProcessingReport returns 404 when incomplete

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#60]
When the ProcessingReport is incomplete the MWS API will return HTTP statuscode 404. The AmazonProcessingReport class checks the HTTP statuscode from the API. When the HTTP statuscode isn't 200 it won't process the XML.

![screen-shot-2015-10-02-at-11 52 20](https://cloud.githubusercontent.com/assets/4153366/10243940/438bdadc-68fc-11e5-8c59-8ca0889120f1.png)

AmazonReport.php:
```php
/**
 * Sends a request to Amazon for a report.
 *
 * Submits a <i>GetReport</i> request to Amazon. In order to do this,
 * a report ID is required. Amazon will send
 * the data back as a response, which can be saved using <i>saveReport</i>.
 * @return boolean <b>FALSE</b> if something goes wrong
 */
public function fetchReport()
{
    if (!array_key_exists('ReportId', $this->options)) {
        $this->log("Report ID must be set in order to fetch it!", 'Warning');
        return false;
    }

    $url = $this->urlbase . $this->urlbranch;
    $query = $this->genQuery();

    if ($this->mockMode) {
        $this->rawreport = $this->fetchMockFile(false);
    } else {
        $response = $this->sendRequest($url, array('Post' => $query));

        if (!$this->checkResponse($response)) {
            return false;
        }

        $this->rawreport = $response['body'];
    }
}
```

AmazonCore.php:
```php
/**
 * Checks whether or not the response is OK.
 *
 * Verifies whether or not the HTTP response has the 200 OK code. If the code
 * is not 200, the incident and error message returned are logged.
 * @param array $r <p>The HTTP response array. Expects the array to have
 * the fields <i>code</i>, <i>body</i>, and <i>error</i>.</p>
 * @return boolean <b>TRUE</b> if the status is 200 OK, <b>FALSE</b> otherwise.
 */
protected function checkResponse($r)
{
    if (!is_array($r) || !array_key_exists('code', $r)) {
        $this->log("No Response found", 'Warning');
        return false;
    }
    if ($r['code'] == 200) {
        return true;
    } else {
        $xml = simplexml_load_string($r['body'])->Error;
        $this->log("Bad Response! " . $r['code'] . " " . $r['error'] . ": " . $xml->Code . " - " . $xml->Message, 'Urgent');
        return false;
    }
}
```

I'll work out a change in my fork. The AmazonReport should not return false when the HTTP statuscode is 404. False indicates that something is wrong.  It should just verify that it returning XML has the status `FeedProcessingResultNotReady`. Perhaps it should only return false when the HTTP statuscode is something other than 200 AND the XML has not got the status `FeedProcessingResultNotReady`. 

Or I could set the XML response (`$response['body']`) in the `$this->rawreport` variable. Then we could access/check the content of the response at anytime. 

Option 1:
```php
$response = $this->sendRequest($url, array('Post' => $query));
$this->rawreport = $response['body'];

if (!$this->checkResponse($response)) {
    return false;
}
```

Option 2:
```php
$response = $this->sendRequest($url, array('Post' => $query));
$raw = $response['body'];
$xml = simplexml_load_string($raw);

if (!$this->checkResponse($response) && $xml->Code !== 'FeedProcessingResultNotReady') {
    return false;
}

$this->rawreport = $raw;
```

**Comment by Peardian** [comment]
My main concern with this, since I have not looked deeply into it, is that the response is a typical Amazon error response. Even though this particular error has a certain meaning, I don't know if it would be right to treat this error differently from any other error, especially if other requests to the same address can give different error messages with the same response code.

I also don't want to make it less apparent when the report has been retrieved successfully. If the "not ready" messages are treated the same way as successful requests, extra code would be needed to distinguish between the two cases.

**Comment by HMAZonderland** [comment]
The core will only return true when the response code is 200. Which makes sense. But when the report data is not available Amazon returns 404. Which is a valid response for the Reports API. It simply means the report is not ready. Therefor there should be some sort of override for the Reports API.

**Comment by Peardian** [comment]
Do you have a case in mind where this behavior would be beneficial? I cannot think of one myself that wouldn't already be solvable using `getLastResponse`.

**Comment by HMAZonderland** [comment]
Well after submitting the feed I would like to know if it succeeded. To do so you would need the ProcessingReport result. I could schedule this through a service that checks the ProcessingReport result. When this returns false I would say something is wrong and stop this scheduled service so it would never check the ProcessingReport result.

**Comment by Peardian** [comment]
You could use an `AmazonReportRequestList` object to see your requested reports and check whether or not the `ReportProcessingStatus` is "`_DONE_`" before attempting to retrieve the results.

**Comment by HMAZonderland** [comment]
You have the ID of the ProcessingReport. Why request a complete list, search for your Report and verify if the status is `_DONE_`. 

Would be easier just to request the `Report`, see if the HTTP_STATUS is 404 (indicating false) and use option 1 or 2 to return the status of the report.

**Comment by Peardian** [comment]
You can filter the list by giving it a list of exactly the ID (or IDs) that you want to see by using `setRequestIds`, if that helps. It might not be as easy as repeatedly asking for the report until it finishes processing, but it is the procedure that Amazon suggests in their API docs.

Anyway, if the errors are treated as success, you risk treating Amazon's error message as the results of your report.

**Comment by HMAZonderland** [comment]
Ah wel. You might have a point here. I'll look into this solution. After all, it is still Amazon we are talking about.

**Comment by Peardian** [comment]
The way error codes are handled won't be changed, but I did add new methods that make it a lot easier to get the Amazon error code.
