### ISSUE TITLE
[Warning] AmazonOrderList.php:340 checkResponse] No Response found

### ISSUE THREAD

**Issue by serchie** [CPIGroup/phpAmazonMWS#61]
I just made my amazon-config.php file:
> $store['NAME']['merchantId'] = 'MyMerchantID';
> $store['NAME']['marketplaceId'] = 'A1RKKUPIHCS9HS';
> $store['NAME']['keyId'] = 'MyKeyID';
> $store['NAME']['secretKey'] = 'MyAccessKey';
> 
> $AMAZON_SERVICE_URL = 'https://mws-eu.amazonservices.com';

Then, removed the die() into /examples/order_examples.php and executed it. I get a blank page, and this error into log.txt:
> [Warning][2015/11/03 11:30:36 guest@xxx.xx.xxx.xxx AmazonOrderList.php:340 checkResponse] No Response found

What I'm doing wrong?

Thanks in advance.

**Comment by Peardian** [comment]
The Amazon service URL requires a slash at the end. (I hope to change that when I have the chance.) The rest of your settings look correct, so you should be able to connect after that.

**Comment by serchie** [comment]
Yeah, that's correct.

I really appreciate your answer. Spent more than an hour trying to understand why it didn't working. 

Thanks a lot.
