### ISSUE TITLE
I want know how to use this library like using mws api

### ISSUE THREAD

**Issue by sharpscar** [CPIGroup/phpAmazonMWS#62]
hello  

I apologize before write this. my english not good.

first I want use requesting method in this library,
 like mws's php library Product in 'ListMathingProducts()'

how can I find function  or which one use  in this library?

**Comment by sharpscar** [comment]
anyone help me 


    $obj_product = new AmazonProductList("abcstore");                 // this is changed by abcstore
            $obj_product->setIdType('ASIN');        // need set id
            $obj_product->setProductIds('B00CL1BPXM');
             $obj_product->fetchProductList();
           $list =    $obj_product->getProduct();

error message  is 
====================================================================
Declaration of AmazonProduct::getProduct() should be compatible with AmazonProductsCore::getProduct($num = NULL)

should I delete or change in method?

**Comment by sharpscar** [comment]
I changed AmazonProduct.php  295 line 

like this  Declaration of A:method should be compatible with B :method 
is different parameter is it right way?

    public function getProduct($num = null){
        return $this->getData();
    }

**Comment by Peardian** [comment]
Yes, that is correct. That Strict Mode error has been fixed in the next version, which is not yet released.

**Comment by sharpscar** [comment]
thank you 
this library helping me.

**Comment by Peardian** [comment]
Since all of the questions have been resolved and the new version is out, I am closing this.
