### ISSUE TITLE
Adding Finance Reports e.g. ListFinancialEvents?

### ISSUE THREAD

**Issue by andreasba** [CPIGroup/phpAmazonMWS#63]
Good evening,

is there any update or release planned which includes the changes made in 2015? For example ListFinancialEvents were added to display the settlement reports:

http://docs.developer.amazonservices.com/en_DE/finances/Finances_Overview.html

Thanks
Andreas

**Comment by Peardian** [comment]
At some point I would like to get the library caught up with all of the updates and new features, but right now I am unable to work on it at all.

**Comment by andreasba** [comment]
Thanks for your quick reply @Peardian and I totally understand.

Did you think about releasing a minor release now so that other people can add other functionality such as the Finance reports for example?

Thanks
Andreas

**Comment by Peardian** [comment]
I would like to, but I am unable to do so, and I have not been able to add support for any new API features since the last release.

**Comment by Peardian** [comment]
Good news, I'm starting on the Finances API right now. As such, I will close this.
