### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by HMAZonderland** [CPIGroup/phpAmazonMWS#64]
The library isn't usable for people running php 7. This is only because `composer.json` should be updated to. 
```json
{
    "name": "cpigroup/php-amazon-mws",
    "type": "library",
    "description": "An open-source library to connect to Amazon's MWS web services in an object-oriented manner, with a focus on intuitive usage.",
    "license": "Apache-2.0",
    "keywords": ["API", "Amazon", "PHP"],
    "require":{
                "php": ">=5.4",
                "ext-curl": "*"
    },
    "require-dev": {
                "phpunit/phpunit": "4.8.*"
                   },
    "autoload": {
        "classmap": ["includes/classes/"]
    }
}
```
To be able to run the test cases under PHP7 `phpunit` should be updated to the most recent version.

The only test case that fails is AmazonOrderListTest::testSetLimits. This is because no error is throw when `strtotime` is supplied with an array. It will simply return false. No exception is thrown. 
Please check: https://github.com/HMAZonderland/phpAmazonMWS/commit/90580c8a680e73f39237936a1fc60967cf0b1e5d and https://github.com/HMAZonderland/phpAmazonMWS/commit/b28ba251b3fdd4d8f1344b59b9510a2c0176a59d

I have updated my source and I can confirm the source works under PHP7.

If you like I can create pull requests?

**Comment by Peardian** [comment]
Thank you for reporting this. You are welcome to make a merge request, though it may be a while before I am able to look into it.

**Comment by HMAZonderland** [comment]
Perhaps we should add a testing service as Travis to run the source code on multiple php versions?

**Comment by Peardian** [comment]
I am not familiar with Travis, but that sounds like it could be useful. Again, it may be a while before I am able to look into it myself.

**Comment by pincombe** [comment]
Hey I would also be happy to help out and get this library working on PHP7. Its currently the only library I use that won't install under PHP7 and as far as i can see there is no reason for the incompatibility. Looking at the number of project forks it looks like a number of people might be actively making the change for themselves and leaving the project behind which would be a same for such a unique library.

**Comment by Peardian** [comment]
This is one of the changes I am hoping to make the next time I am able to work on the library, which should be very soon.

On a side note relating to this issue, I have since learned about Travis and added support for it. All of the tests pass under PHP7, which is strange because I was expecting the error mentioned in the first post. I haven't had a chance to look into it, which is why I did not make the change during the last round of updates.

**Comment by pincombe** [comment]
Hey no worries I totally understand how difficult it is to manage time between projects especially when the project is open source. 

I'm having no problems using this library in PHP7 after forking the project and increasing the allowed php version. 

Let me know if there is anything I can help you with.

**Comment by Peardian** [comment]
I did research into PHP7 and now I know why the test fails (or should fail). I'm going to make a pull request soon that take care of both the PHP version and the test.

**Comment by Peardian** [comment]
taken care of
