### ISSUE TITLE
order_examples.php

### ISSUE THREAD

**Issue by whitegoat** [CPIGroup/phpAmazonMWS#65]
Hello,

I am testing the php code in local host. but the response print in the document window like this.
There was a problem with the Amazon library. Error: Config file does not exist or cannot be read! (/Applications/AMPPS/www/phpAmazon/includes/classes/../../amazon-config.php)

What was the issues.

Thanks,

**Comment by Peardian** [comment]
Did you create the config file like the instructions in `INSTALL.md` say to do? If you did create the file, check the file's permissions and allow PHP to access it.

**Comment by Peardian** [comment]
Since there has not yet been a response, I am assuming that the problem was resolved and that this can be closed.
