### ISSUE TITLE
ShipmentServiceLevelCategory

### ISSUE THREAD

**Issue by ahmettok** [CPIGroup/phpAmazonMWS#74]
When we fetch orders from Amazon on XML the field is called ShipmentServiceLevelCategory but on library it is called ShipServiceLevelCategory that causes orders not having shipping method set. changing it everywhere fixed the issue.

**Comment by Peardian** [comment]
Thank you for finding this issue. This must have been a mistake on my part, because I cannot find any old references to the field name I used. I will fix it as soon as I am able to.

**Comment by Peardian** [comment]
I found where the issue came from. In the document I have from March 2014, the parameter is called "ShipServiceLevelCategory". It seems that, at some point, they renamed it in both versions of the Orders API.

**Comment by Peardian** [comment]
taken care of
