### ISSUE TITLE
List one order by id

### ISSUE THREAD

**Issue by joetorro** [CPIGroup/phpAmazonMWS#76]
Question: what's the code to retrieve the details of just one order by id?  I can list loads of them but I just need to list one at a time.

Thanks

Joe

(BTW, great plugin)

**Comment by Peardian** [comment]
There are three ways you can do this:

1. Create an `AmazonOrder` object, set the order ID, and use `fetchOrder()`.
2. Create an `AmazonOrderSet` object, set the order ID (or multiple IDs), and use `fetchOrders()`.
3. Create an `AmazonOrderList` object, set the seller order ID filter, and use `fetchOrders()`. (This only only works if the orders have unique Seller Order IDs associated with them.)

I'm glad you like the library. A lot of effort was put into designing and documenting it, so I recommend reading the descriptions at the top of each class. Each description says what the class can do, what options are required, and what to use it for.

**Comment by joetorro** [comment]
Thanks Peardian.  It turns out I was missing fetchOrder:

```
private function get_single_order($amazon_order_id)
  {
        require('path/includes/classes.php'); 
        try {
            $amz = new AmazonOrder("myStore"); 
            $amz->setOrderId($amazon_order_id); 
            $amz->fetchOrder(); 
            return $amz->getData();
        } catch (Exception $ex) {
            echo 'There was a problem with the Amazon library. Error: '.$ex->getMessage();
        }
}
```
