### ISSUE TITLE
Add support for UpdateFulfillmentOrder action from Fulfillment Outbound Shipment API

### ISSUE THREAD

**Issue by bfrost2893** [CPIGroup/phpAmazonMWS#85]
Hello,

Is there any plan to add the [UpdateFulfillmentOrder action](http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_UpdateFulfillmentOrder.html) to go along with the `AmazonFulfillmentOrderCreator` (maybe there should be an 'updater')? I would like to be able to put orders on hold and then update the fulfillment order once it has been paid. Some e-commerce websites allow users to create orders without paying and let the seller facilitate payment how they please, so this would be useful for that.

I don't think it would be difficult to add this. I could maybe work on a PR for this after discussing what the changes should be to the API.

Thanks!
Brad

**Comment by Peardian** [comment]
Yes, actually, it was just added to the master dev branch two days ago. It will still be at least a couple of weeks before the next release is ready, though.

**Comment by bfrost2893** [comment]
Great, thanks for the response!
