### ISSUE TITLE
Hello, need help.

### ISSUE THREAD

**Issue by shirie** [CPIGroup/phpAmazonMWS#86]
hello. I want to upload good to my different amazon accounts. I tried the codes, using the SubmitFeed interface, and it works well when uploading to my first account. 
I use other account to give  "developer access" to my first account and get an auth-token. So how to use the token and my first account to upload goods to the other account. Can you help? Thanks.

**Comment by Peardian** [comment]
I think the auth token you received should be put as the `MWSAuthToken` in your config file. I am not completely certain because I have not used the MWSAuthToken feature before.

**Comment by shirie** [comment]
Thanks @Peardian  for your reply.
I didn't find the MWSAuthToken item in the config template. I grep it in all the codes and no match items either. So. err....
I didn't find any doc in the amazon document. Can someone give me some guide, I guess I may miss something... Thanks

**Comment by Peardian** [comment]
Oh, my apologies. I forgot that MWSAuthToken support is still only in the master dev branch. I don't know when the next release will be.

**Comment by Peardian** [comment]
The next version has entered Release Candidate phase, so I suppose I can close this now.
