### ISSUE TITLE
Action GetMyFeesEstimate not implemented

### ISSUE THREAD

**Issue by haffoudhi** [CPIGroup/phpAmazonMWS#92]
The action GetMyFeesEstimate is missing. it this for a reason ?

**Comment by Peardian** [comment]
That action must be relatively new, because I have not heard about it until now. I can add it to version 1.4, since 1.3 is just about ready to release. Thank you for calling attention to it.

**Comment by Peardian** [comment]
The feature was apparently added on the 1st of June, the same day that I merged the products API updates. What timing!

**Comment by TwassistantKeith** [comment]
I would also love to see this implemented.

**Comment by GAMITG** [comment]
Is `GetMyFeesEstimate` feature added to master branch?

**Comment by Peardian** [comment]
Not yet, unfortunately.

**Comment by GAMITG** [comment]
I need `GetMyFeesEstimate` feature for my application. can you help me?

**Comment by haffoudhi** [comment]
I have implemented this feature mysef, it may be incomplete, but it's enough for me to get TotalFeesEstimate and ReferralFee.
I have attached two files, overwrite the current files with my files.
To call fees function, use the next code:
```
      $amz = new AmazonProductFees($store, false, null, $mws_config);
      $amz->setMarketPlaceIds($marketplace_id);
      $amz->setIdTypes("ASIN");
      $amz->setProductIds($ASIN);
      $amz->setAmazonFullfilleds("true");
      $amz->setIdentifiers("request1");
      $amz->setAmounts((string)$price);
      $amz->setCurrencyCodes($currency); // e.g; USD
      $amz->fetchEstimationFees();
      $product_fees = $amz->getProduct();
      if(!empty($product_fees)) {
            foreach ($product_fees as $match) {
                  $fees = $match->getProduct();
                  return $fees['TotalFeesEstimate']; // or return $fees['ReferralFee'];
            }
      }
```
To extract more fees values for mws response, you can update AmazonProduct.php > function loadFees($xml). 


[mws fees.zip](https://github.com/CPIGroup/phpAmazonMWS/files/973633/mws.fees.zip)

**Comment by GAMITG** [comment]
Thank you @haffoudhi  for saving my time.

**Comment by GAMITG** [comment]
I think you forgot to send me `AmazonProductCore.php` file.

**Comment by haffoudhi** [comment]
i have attached AmazonProductCore.php with the other two files.
[mws fees 3 files.zip](https://github.com/CPIGroup/phpAmazonMWS/files/979031/mws.fees.3.files.zip)

**Comment by GAMITG** [comment]
Thank you again @haffoudhi

**Comment by Peardian** [comment]
Support for `GetMyFeesEstimate` has been added to the master dev branch!
