### ISSUE TITLE
SalesRank not parsed correctly

### ISSUE THREAD

**Issue by haffoudhi** [CPIGroup/phpAmazonMWS#93]
e,g; ASIN: B00NCQZLM6
$amz = new AmazonProductList("StoreName");
$amz->setIdType("ASIN");
$amz->setProductIds($ASIN);
$amz->fetchProductList();
return $amz->getProduct();

your code returns the last salesrank, while the api is returning multiple saleranks.

**Comment by Peardian** [comment]
That sounds like a bug, but I think that bug might be fixed already. Which version are you using?

**Comment by haffoudhi** [comment]
i m using the stable version, last one i guess.
// file includes/classes/AmazonProduct.php
        //SalesRankings
        if ($xml->SalesRankings){
            foreach($xml->SalesRankings->children() as $x){
                foreach($x->children() as $y){
                    $this->data['SalesRankings'][$x->getName()][$y->getName()] = (string)$y;
                }
            }
        }
this is where parsing of SalesRankings happens.

**Comment by Peardian** [comment]
In that case, the bug has already been fixed in the next version. The release candidate for the next version is available, in case you want to try it. (More info here: #91)

I'll close this for now, but I can open it again if you find that the new version does not fix the problem.
