### ISSUE TITLE
PHP 7  does not satisfy that requirement.

### ISSUE THREAD

**Issue by mohamedziada** [CPIGroup/phpAmazonMWS#94]
When i try to install on my server with PHP 7.0.9
Problem 
    - Installation request for cpigroup/php-amazon-mws ^1.2 -> satisfiable by cpigroup/php-amazon-mws[1.2.0].
    - cpigroup/php-amazon-mws 1.2.0 requires php ~5.4 -> your PHP version (7.0.9) does not satisfy that requirement.

Thank you

**Comment by Peardian** [comment]
Yes, this issue has already been addressed and the next version (which is in release candidate phase right now) will allow for newer versions of PHP.
