### ISSUE TITLE
Set Order Status

### ISSUE THREAD

**Issue by HeXtheone** [CPIGroup/phpAmazonMWS#99]
Hello,

i fetch my orders from Amazon, that works great.
But how I can conform the delivery with trackingcode to amazon?

I found this sample:  

`/*
				 * <?xml version="1.0" encoding="UTF-8"?>
				<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amznenvelope.xsd">
				<Header>
				<DocumentVersion>1.01</DocumentVersion>
				<MerchantIdentifier>My Store</MerchantIdentifier>
				</Header>
				<MessageType>OrderFulfillment</MessageType>
				<Message>
				<MessageID>1</MessageID>
				<OrderFulfillment>
				<MerchantOrderID>1234567</MerchantOrderID>
				<MerchantFulfillmentID>1234567</MerchantFulfillmentID>
				<FulfillmentDate>2002-05-01T15:36:33-08:00</FulfillmentDate>
				<FulfillmentData>
				<CarrierCode>UPS</CarrierCode>
				<ShippingMethod>Second Day</ShippingMethod>
				<ShipperTrackingNumber>1234567890</ShipperTrackingNumber>
				</FulfillmentData>
				<Item>
				<MerchantOrderItemID>1234567</MerchantOrderItemID>
				<MerchantFulfillmentItemID>1234567</MerchantFulfillmentItemID>
				<Quantity>2</Quantity>
				Selling on Amazon – Guide to XML
				67
				</Item>
				</OrderFulfillment>
				</Message>
				</AmazonEnvelope>
				 */`

**Comment by Peardian** [comment]
There are two ways to do tracking numbers: the Merchant Fulfillment API (the sample you found) and a shipment feed.

If you have not already purchased a tracking number, you can use the Merchant Fulfillment API to purchase a tracking number directly through Amazon. Keep in mind that Amazon will provide rates for all available services, including those that would arrive late or would not make sense for your item. (You can't ship a toaster in an envelope.) If you purchase a tracking number this way, Amazon will already know about the tracking number, so no further action is needed.

If you have already purchased a tracking number through another service, you must send an Order Fulfillment Feed ("_POST_ORDER_FULFILLMENT_DATA_") using the Feeds API. This library can send feeds, but it cannot build them, so you will have to look on Amazon's website for a template.

That's all there is to it. Hopefully this helps. I'll close this later today unless you still need help.

**Comment by HeXtheone** [comment]
thank you,

one more question:

setFeedContent(): set the full xml ? like <?xml version="1.0" encoding="UTF-8"?> <AmazonEnvelope ....
or just the Body like <Message>... </Message> ?

**Comment by Peardian** [comment]
Yes, it should be the full XML contents. (Or, in the case of flat file feeds, the full CSV contents.)

**Comment by HeXtheone** [comment]
But what is wrong, i get alway Errorcode 25.

```
$feed = '<?xml version="1.0" encoding="UTF-8"?>
					<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
					<Header>
						<DocumentVersion>1.01</DocumentVersion>
						<MerchantIdentifier>XXXXXX</MerchantIdentifier>
					</Header>
					<MessageType>OrderFulfillment</MessageType>
						<Message>
							<MessageID>1</MessageID>
						 	<OrderFulfillment>
								<AmazonOrderID>amazonOrderId</AmazonOrderID>
							<FulfillmentDate>2016-09-01T12:36:33+02:00</FulfillmentDate>
								<FulfillmentData>
									<CarrierCode>UPS</CarrierCode>
									<CarrierName>UPS</CarrierName>
									<ShippingMethod>Second Day</ShippingMethod>
					<ShipperTrackingNumber>1Z201R596893249019</ShipperTrackingNumber>
								</FulfillmentData>
								<Item>
			<AmazonOrderItemCode>32517265691075</AmazonOrderItemCode>
			<Quantity>1</Quantity>
					</Item>
							 </OrderFulfillment>
						</Message>
					</AmazonEnvelope>';

$f = new AmazonFeed();

				$f->setFeedContent($feed);
				$f->setFeedType('_POST_ORDER_FULFILLMENT_DATA_');

				$f->submitFeed();
```

**Comment by Peardian** [comment]
The error you are getting is related to the contents of the feed itself, which is beyond the scope of the library.
